name: example
description: "Audio Flux example."
publish_to: 'none'
version: 0.1.2

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  flutter_recorder: ^1.1.2
    # path: ../flutter_recorder
  flutter_soloud: 3.4.10
    # path: ../flutter_soloud
  audio_flux:
    path: ../

  logging: ^1.3.0
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audio/

  shaders:
    - shaders/2d_led_spectrum.frag
    - shaders/frequency_visualization.frag
    - shaders/sound_eclipse_rpm.frag
    - shaders/audio_wave_form.frag
    - shaders/sound_sinus_wave.frag
    - shaders/audio_visualizer_raymarching.frag
    - shaders/sound_grid.frag
    - shaders/smoke_rings.frag
    - shaders/dancing_flutter.frag
    - shaders/texture.frag
